import { useRef } from 'react'
import { useInViewOnce } from '../hooks/useInViewOnce.js'
import { useLanguage } from '../context/LanguageContext.jsx'
import { useContent } from '../context/ContentContext.jsx'
import { localize } from '../utils/localize.js'
import { InternalLink } from '../utils/router.jsx'
import TerminalWindow from './TerminalWindow.jsx'
function Card({project,index,visible}){const ref=useRef(),{t,language}=useLanguage(),name=localize(project.name,language);const move=e=>{if(!matchMedia('(pointer:fine)').matches)return;const r=ref.current.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;ref.current.style.setProperty('--tilt-x',`${(.5-y)*8}deg`);ref.current.style.setProperty('--tilt-y',`${(x-.5)*9}deg`)};const reset=()=>{ref.current.style.setProperty('--tilt-x','0deg');ref.current.style.setProperty('--tilt-y','0deg')};return <article ref={ref} className={`project-card project-card--tilt reveal ${visible?'visible':''}`} style={{transitionDelay:`${index*120}ms`}} onPointerMove={move} onPointerLeave={reset}><span className="project-scan"/><div className="project-preview"><img src={project.image||'/assets/projects/educrm.svg'} alt={name} loading="lazy"/></div><div className="project-tabs"><span className="project-tab active"><span className="file-dot"/>{project.file||`${name}.jsx`}</span><span className="project-tab">{project.secondTab||'server/api.js'}</span></div><div className="project-card-body"><h3>{name}</h3><p>{localize(project.description,language)}</p><div className="project-stack">{(project.stack||[]).map(x=><span key={x}>{x}</span>)}</div></div><div className="project-footer"><div className="project-footer-links">{project.live&&project.live!=='#'?<a className="project-link project-link--live" href={project.live} target="_blank" rel="noreferrer">Saytni ochish ↗</a>:null}{project.github&&project.github!=='https://github.com/'?<a className="project-link" href={project.github} target="_blank" rel="noreferrer">GitHub ↗</a>:null}</div><InternalLink className="project-link" href={`/project/${project.slug}`}>{t('projects.details')} ↗</InternalLink></div></article>}
export default function Projects(){const [ref,v]=useInViewOnce({threshold:.08}),{t}=useLanguage(),{content}=useContent();const items=(content.projects||[]).filter(x=>x.active!==false);return <section className="section" id="projects" ref={ref}><div className="container"><TerminalWindow title="~/portfolio/projects"><div className="terminal-body"><div className={`reveal ${v?'visible':''}`}><span className="section-label">{t('projects.label')}</span><h2 className="section-title">{t('projects.title')}</h2><p className="section-subtitle">{t('projects.subtitle')}</p></div><div className="projects-grid">{items.map((x,i)=><Card project={x} index={i} visible={v} key={x.id}/>)}</div></div></TerminalWindow></div></section>}
